cakes/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
import debug_toolbar

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'themes/', include('themes.urls', namespace='themes')),
    url(r'customer/', include('customer.urls', namespace='customer')),
    # url(r'auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

customer/urls.py
from django.conf.urls import url
from django.contrib.auth import views as customer_views
from . import views
from django.urls import reverse, reverse_lazy

app_name = 'customer'

urlpatterns = [
    url(r'^signup/$', views.customer_signup, name='customer-signup'),
    url(r'^profile/$', views.customer_profile, name='customer-profile'),
    url(r'^profiledata/$', views.customer_json_profile, name='customer-profile-data'),

    url(r'^logout/$', customer_views.LogoutView.as_view(), {'next_page': 'customer:customer-login'}, name='customer-logout'),
    url(r'^login/$', customer_views.login, {'template_name': 'customer/login.html'}, name='customer-login'),

    # Activation
    url(r'^account_activation_sent/$', views.account_activation_sent, name='customer_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='customer_activate'),

    # Loggedin Users
    url(r'^settings/password/$', customer_views.PasswordChangeView.as_view(
        template_name='customer/settings/password_change.html',
        success_url = reverse_lazy('customer:customer_password_change_done')),
        name='customer_settings_password_change'),
    url(r'^settings/password/done/$',
        customer_views.PasswordChangeDoneView.as_view(
            template_name='customer/settings/password_change_done.html'),
        name='customer_password_change_done'),

    # Unloggedin Users
    url(r'^password/reset/$', customer_views.PasswordResetView.as_view(
        template_name='customer/password/reset.html',
        email_template_name='customer/password/reset_email.html',
        subject_template_name='customer/password/reset_subject.txt',
        success_url = reverse_lazy('customer:customer_password_reset_done')),
        name='customer_password_reset'),

    url(r'^password/reset/done/$', customer_views.PasswordResetDoneView.as_view(
        template_name='customer/password/reset_done.html'),
        name='customer_password_reset_done'),


    url(r'^password/reset/comfirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        customer_views.PasswordResetConfirmView.as_view(
            template_name='customer/password/reset_confirm.html',
            success_url = reverse_lazy('customer:customer_password_reset_complete')),
        name='customer_password_reset_confirm'),

    url(r'^reset/complete/$',
        customer_views.PasswordResetCompleteView.as_view(
            template_name='customer/password/reset_complete.html'),
        name='customer_password_reset_complete'),

]

customer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model

class User(AbstractUser):
    class Meta:
        db_table = 'auth_user'

    def is_customer(self):
        """ A customer is marked as this"""
        return self.is_customer

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_customer = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    street = models.CharField(max_length=128, blank=True, null=True)
    house_number = models.CharField(max_length=128, blank=True, null=True)
    house_number_ext = models.CharField(max_length=128, blank=True, null=True)
    postcode = models.CharField(max_length=128, blank=True, null=True)
    city = models.CharField(max_length=128, blank=True, null=True)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return '{} {} => from - {}'.format(self.user.first_name, self.user.last_name, self.city)

@receiver(post_save, sender=get_user_model())
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

customer/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
import datetime


class SignUpForm(UserCreationForm):
    birth_date = forms.DateField(widget = forms.SelectDateWidget())

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'birth_date', 'password1', 'password2')

customer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import authenticate, views, login, logout
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from .forms import SignUpForm
from django.shortcuts import render, redirect, render_to_response
from .tokens import account_activation_token
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.core import serializers
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.models import User
from .models import User, UserProfile
import json

@login_required
def customer_profile(request):
    """
    Customer Profile
    :param request:
    :return:
    """
    return render(request, 'customer/customer_profile.html', {})

def customer_json_profile(request):
    if request.user.is_active:
        user_pk = request.user.id
        user = UserProfile.objects.filter(pk=user_pk).select_related('user').first()
        data = serializers.serialize('json', [user, ])
        structure = json.loads(data)
        data = json.dumps(structure[0])
        return HttpResponse(data, content_type='application/json')
    
def customer_signup(request):
    """
    User sign Up view
    :param request:
    :return:
    """
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            # User
            customer = form.save(commit=False)
            customer.is_active = False
            customer.save()

            # Profile
            customer.refresh_from_db()
            customer.userprofile.birth_date = form.cleaned_data.get('birth_date')
            customer.userprofile.is_customer = True
            customer.userprofile.save()

            # Activation Email
            current_site = get_current_site(request)
            subject = 'Activate Your CakesandMore Account'
            message = render_to_string('customer/activation/email.html', {
                'user': customer,
                'domail': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(customer.pk)),
                'token': account_activation_token.make_token(customer)
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(subject, message, to=[to_email])
            email.send()
            return redirect('customer:customer_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'customer/signup.html', {'form': form})


def customer_logout(request):
    """
    :param request:
    """
    logout(request)


def account_activation_sent(request):
    """

    :param request:
    :return:
    """
    return render(request, 'customer/activation/sent.html')


def activate(request, uidb64, token):
    """
    Activate Users
    :param request:
    :param uidb64:
    :param token:
    :return:
    """
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = get_user_model()
        customer = user.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None

    if customer is not None and account_activation_token.check_token(customer, token):
        customer.is_active = True
        customer.save()
        customer.userprofile.email_confirmed = True
        customer.userprofile.save()
        login(request, customer)
        return redirect('customer:customer-profile')
    else:
        return render(request, 'customer/activation/invalid.html')

customer/templates/customer/base.html
{% extends 'base.html' %}
{% load static i18n sekizai_tags cms_tags %}

{% block navbar %}
    <a href="#">Projects</a>
    <hr>
{% endblock %}

{% block title %}Customer Account {% endblock %}
{% block content %}
<ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
    
{% endblock %}

customer/templates/customer/customer_profile.html
{% extends 'customer/base.html' %}

{% block content %}
  <div id="profile"></div>
    <p>Profile </p> 
    <address>
          <strong>Twitter, Inc.</strong><br>
          {{ user.userprofile.street }} {{ user.userprofile.house_number }}<br>
          {{ user.userprofile.postcode }} {{ user.userprofile.city }}<br>
          <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
        
        <address>
          <strong>{{ user.first_name }} {{ user.last_name }}</strong><br>
          <a href="mailto:#"> {{ user.email }}</a>
        </address>
{% endblock %}

customer/templates/customer/login.html
{% extends 'customer/base.html' %}
{% load cms_tags i18n sekizai_tags static %}

{% block content %}
<div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
<div class="card bg-light mb-3">
    <div class="card-header">
        <a href="{% url 'customer:customer-login' %}">CakesAndMore:</a> <span class="float-right">Login in to Your Account</span>
    </div>
        <div class="card-body">
          <h3 class="card-title">Sign in</h3>
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>{% trans "Your username and password didn't match. Please try again." %}</strong>
                    </div>
                {% endif %}

                {% if next %}
                    {% if user.is_authenticated %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <strong>Holy guacamole!</strong>
                            {% trans "Your account doesn't have access to this page. To proceed please login with an account that has access." %}.
                        </div>
                    {% else %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <strong>{% trans 'Please login to see this page.' %}</strong>
                        </div>
                    {% endif %}
                {% endif %}

                <form method="post" action="{% url 'customer:customer-login' %}" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group row">
                            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                            <div class="col-sm-10">
                                <input autofocus id="{{ field.id_for_label }}" name="{{ field.name }}" type="{% if field.name == 'password' %}password{% else %}text{% endif %}" required class="form-control">
                            </div>
                        </div>
                    {% endfor %}
                    <div class="spacer"></div>
                    <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                            <button type="submit" class="btn btn-primary">{% trans 'Log in' %}</button>
                        </div>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}" />

                </form>
            </div>
            <div class="card-footer text-muted text-center">
                <div class="d-flex justify-content-around">
                    <span class="p2"><a href="{% url 'customer:customer-signup' %}">No account Yet?</a></span>
                    <span class="p2">Already have an account? <a href="{% url 'customer:customer-login'%}">Log in</a></span> 
                    <span class="p2"><a href="{% url 'customer:customer_password_reset' %}">Lost password?</a></span>
                </div>
            </div>
        </div>
        </div>
        </div>
{% endblock %}
<form>
    <div class="col-sm-10">
        <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
    </div>
    <div class="form-group row">
    </div>
</form>
</div>

customer/templates/customer/signup.html
{% extends 'customer/base.html' %}

{% load i18n %}

{% block content %}
{% if user.is_authenticated %}
  <span class="alert alert-info"> {{ user.first_name }}, You are already logged in.</span>
  <span class="alert alert-info"><a href="">Log Out?</a> </span>
{% else %}
  <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 col-md-10 col-sm-12">
          <div class="card bg-light mb-3">
              <div class="card-header">
                  <a href="{% url 'customer:customer-login' %}">CakesAndMore:</a> <span class="float-right">Signup for a new Account</span>
              </div>
            <div class="card-body">
              <h3 class="card-title">Sign up</h3>
              {% if form.errors %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
                  <strong>{% trans "You must fill in all fields to proceed. Please try again." %}</strong>
              </div>
              {% endif %}

              {% if next %}
              {% if user.is_authenticated %}
                  <div class="alert alert-warning alert-dismissible fade show" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                      <strong>Holy guacamole!</strong>
                      {% trans "Your account doesn't have access to this page. To proceed please login with an account that has access." %}.
                  </div>
              {% else %}
                  <div class="alert alert-danger alert-dismissible fade show" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                      <strong>{% trans 'Please login to see this page.' %}</strong>
                  </div>
              {% endif %}
              {% endif %}
              <form method="post" novalidate>
                  {% csrf_token %}
                  {% for field in form %}
                      <div class="row">
                        <div class="col-sm-4"></div>
                        <div class="col-sm-8">
                            {% for error in field.errors %}
                            <p class="text text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                      </div>
                      <div class="form-group row">
                          <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label }}</label>
                          <div class="col-sm-8">
                              <input autofocus id="{{ field.id_for_label }}" 
                                      name="{{ field.name }}" 
                                      type="{% if field.name == 'password1' or field.name == 'password2' %}password{% elif field.name == 'birth_date' %}date{% else %}text{% endif %}" 
                                      required class="form-control">
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-sm-4"></div>
                          <div class="col-sm-8">
                              {% if field.help_text %}
                              <small class="text text-primary"">{{ field.help_text }}</small>
                              {% endif %}
                          </div>
                        </div>
                  {% endfor %}
                  <div class="spacer"></div>
                </p>
                <button type="submit" class="btn btn-primary btn-block">Create an account</button>
              </form>
            </div>
            <div class="card-footer text-muted text-center">
              Already have an account? <a href="{% url 'customer:customer-login'%}">Log in</a>
            </div>
          </div>
          </div>
          </div>
    </div>
{% endif %}
{% endblock %}