cakes/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
import debug_toolbar

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'themes/', include('themes.urls', namespace='themes')),
    url(r'customer/', include('customer.urls', namespace='customer')),
    # url(r'auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

customer/urls.py
from django.conf.urls import url
from django.contrib.auth import views as customer_views
from . import views
from django.urls import reverse, reverse_lazy

app_name = 'customer'

urlpatterns = [
    url(r'^signup/$', views.customer_signup, name='customer-signup'),
    url(r'^profile/$', views.customer_profile, name='customer-profile'),
    url(r'^profiledata/$', views.customer_json_profile, name='customer-profile-data'),

    url(r'^logout/$', customer_views.LogoutView.as_view(), {'next_page': 'customer:customer-login'}, name='customer-logout'),
    url(r'^login/$', customer_views.login, {'template_name': 'customer/login.html'}, name='customer-login'),

    # Activation
    url(r'^account_activation_sent/$', views.account_activation_sent, name='customer_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='customer_activate'),

    # Loggedin Users
    url(r'^settings/password/$', customer_views.PasswordChangeView.as_view(
        template_name='customer/settings/password_change.html',
        success_url = reverse_lazy('customer:customer_password_change_done')),
        name='customer_settings_password_change'),
    url(r'^settings/password/done/$',
        customer_views.PasswordChangeDoneView.as_view(
            template_name='customer/settings/password_change_done.html'),
        name='customer_password_change_done'),

    # Unloggedin Users
    url(r'^password/reset/$', customer_views.PasswordResetView.as_view(
        template_name='customer/password/reset.html',
        email_template_name='customer/password/reset_email.html',
        subject_template_name='customer/password/reset_subject.txt',
        success_url = reverse_lazy('customer:customer_password_reset_done')),
        name='customer_password_reset'),

    url(r'^password/reset/done/$', customer_views.PasswordResetDoneView.as_view(
        template_name='customer/password/reset_done.html'),
        name='customer_password_reset_done'),


    url(r'^password/reset/comfirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        customer_views.PasswordResetConfirmView.as_view(
            template_name='customer/password/reset_confirm.html',
            success_url = reverse_lazy('customer:customer_password_reset_complete')),
        name='customer_password_reset_confirm'),

    url(r'^reset/complete/$',
        customer_views.PasswordResetCompleteView.as_view(
            template_name='customer/password/reset_complete.html'),
        name='customer_password_reset_complete'),

]

themes/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'themes'

urlpatterns = [
    url(r'^make_own_recept/$', views.create_cake_receipt, name='own_recept'),
    url(r'^cake_list/$', views.CakeListView.as_view(), name='cake_list'),
    url(r'^user_list/$', views.UserListView.as_view(), name='user_list'),
    url(r'^user_detail/(?P<pk>[0-9]+)$', views.UserListView.as_view(), name='user_detail'),
    url(r'^cake_detail/(?P<pk>[0-9]+)/$', views.CakeDetailView.as_view(), name='cake_detail')
]

urlpatterns = format_suffix_patterns(urlpatterns)

cakes/templates/base.html
{% load i18n cms_tags staticfiles sekizai_tags menu_tags %}
{% load render_bundle from webpack_loader %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}This is my new project home page{% endblock title %}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        
        {% render_block "css" %}
        {% addtoblock 'css' %}
            {% render_bundle 'themes' 'css' %}
            {% render_bundle 'customer' 'css' %}
        {% endaddtoblock %}
    </head>
    <body>
        <div class="container">
            <div id="navbar" class="">
                <div class="d-flex justify-content-between">
                    <div class="mr-auto p-2">Welcome to CakeGirls</div>
                    <div class="p-2">
                            {% if user.is_authenticated %} 
                                    <a href="{% url 'customer:customer-profile' %}">
                                        <i class="ion-android-person"></i>
                                        <span>Welcome, {{ user.first_name }}</span>
                                    </a>
                                    <span class="separator">|</span>
                                    
                                    <a class="text text-danger" href="{% url 'customer:customer-logout' %}"><i class='ion-log-out'></i> Log Out</a>
                            {% else %}
                                <a href="{% url 'customer:customer-login' %}">
                                    <i class="ion-android-person"></i>
                                    <span>My CakeGirls</span>
                                </a>
                            {% endif %}
                    </div> 
                    <div class="p-2">
                        <span class="separator">|</span>
                            <a href="{% url 'themes:own_recept'%}">
                                <i class="ion-android-cart"></i>
                                <span>Shopping Cart</span>
                            </a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            {% block content %}
                    
            {% endblock content %}
        </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
        {% render_block "js" %}
        {% addtoblock 'js' %}
            {% render_bundle 'themes' 'js' %}
            {% render_bundle 'customer' 'js' %}
        {% endaddtoblock %}
    </body>
</html>

cakes/templates/feature.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="jumbotron">
        {% placeholder "feature" %}
    </div>
    <div>
        {% placeholder "content" %}
    </div>
{% endblock content %}

cakes/templates/menu.html
{% load i18n menu_tags cache %}

{% for child in children %}
    <li class="{% if child.ancestor %}ancestor{% endif %}
        {% if child.selected %} active{% endif %}
        {% if child.children %} dropdown{% endif %}">
        {% if child.children %}
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                {{ child.get_menu_title }} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
            </ul>
        {% else %}
            <a href="{{ child.get_absolute_url }}"><span>{{ child.get_menu_title }}</span></a>
        {% endif %}
    </li>
    {% if class and forloop.last and not forloop.parentloop %}{% endif %}
{% endfor %}

cakes/templates/page.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    {% placeholder "content" %}
{% endblock content %}