cakes/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
import debug_toolbar

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'themes/', include('themes.urls', namespace='themes')),
    url(r'customer/', include('customer.urls', namespace='customer')),
    # url(r'auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

customer/urls.py
from django.conf.urls import url
from django.contrib.auth import views as customer_views
from . import views
from django.urls import reverse, reverse_lazy

app_name = 'customer'

urlpatterns = [
    url(r'^signup/$', views.customer_signup, name='customer-signup'),
    url(r'^profile/$', views.customer_profile, name='customer-profile'),
    url(r'^profiledata/$', views.customer_json_profile, name='customer-profile-data'),

    url(r'^logout/$', customer_views.LogoutView.as_view(), {'next_page': 'customer:customer-login'}, name='customer-logout'),
    url(r'^login/$', customer_views.login, {'template_name': 'customer/login.html'}, name='customer-login'),

    # Activation
    url(r'^account_activation_sent/$', views.account_activation_sent, name='customer_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='customer_activate'),

    # Loggedin Users
    url(r'^settings/password/$', customer_views.PasswordChangeView.as_view(
        template_name='customer/settings/password_change.html',
        success_url = reverse_lazy('customer:customer_password_change_done')),
        name='customer_settings_password_change'),
    url(r'^settings/password/done/$',
        customer_views.PasswordChangeDoneView.as_view(
            template_name='customer/settings/password_change_done.html'),
        name='customer_password_change_done'),

    # Unloggedin Users
    url(r'^password/reset/$', customer_views.PasswordResetView.as_view(
        template_name='customer/password/reset.html',
        email_template_name='customer/password/reset_email.html',
        subject_template_name='customer/password/reset_subject.txt',
        success_url = reverse_lazy('customer:customer_password_reset_done')),
        name='customer_password_reset'),

    url(r'^password/reset/done/$', customer_views.PasswordResetDoneView.as_view(
        template_name='customer/password/reset_done.html'),
        name='customer_password_reset_done'),


    url(r'^password/reset/comfirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        customer_views.PasswordResetConfirmView.as_view(
            template_name='customer/password/reset_confirm.html',
            success_url = reverse_lazy('customer:customer_password_reset_complete')),
        name='customer_password_reset_confirm'),

    url(r'^reset/complete/$',
        customer_views.PasswordResetCompleteView.as_view(
            template_name='customer/password/reset_complete.html'),
        name='customer_password_reset_complete'),

]

customer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model

class User(AbstractUser):
    class Meta:
        db_table = 'auth_user'

    def is_customer(self):
        """ A customer is marked as this"""
        return self.is_customer

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_customer = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    street = models.CharField(max_length=128, blank=True, null=True)
    house_number = models.CharField(max_length=128, blank=True, null=True)
    house_number_ext = models.CharField(max_length=128, blank=True, null=True)
    postcode = models.CharField(max_length=128, blank=True, null=True)
    city = models.CharField(max_length=128, blank=True, null=True)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return '{} {} => from - {}'.format(self.user.first_name, self.user.last_name, self.city)

@receiver(post_save, sender=get_user_model())
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

customer/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
import datetime


class SignUpForm(UserCreationForm):
    birth_date = forms.DateField(widget = forms.SelectDateWidget())

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'birth_date', 'password1', 'password2')

customer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import authenticate, views, login, logout
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from .forms import SignUpForm
from django.shortcuts import render, redirect, render_to_response
from .tokens import account_activation_token
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.core import serializers
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.models import User
from .models import User, UserProfile
import json

@login_required
def customer_profile(request):
    """
    Customer Profile
    :param request:
    :return:
    """
    return render(request, 'customer/customer_profile.html', {})

def customer_json_profile(request):
    if request.user.is_active:
        user_pk = request.user.id
        user = UserProfile.objects.filter(pk=user_pk).select_related('user').first()
        data = serializers.serialize('json', [user, ])
        structure = json.loads(data)
        data = json.dumps(structure[0])
        return HttpResponse(data, content_type='application/json')
    
def customer_signup(request):
    """
    User sign Up view
    :param request:
    :return:
    """
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            # User
            customer = form.save(commit=False)
            customer.is_active = False
            customer.save()

            # Profile
            customer.refresh_from_db()
            customer.userprofile.birth_date = form.cleaned_data.get('birth_date')
            customer.userprofile.is_customer = True
            customer.userprofile.save()

            # Activation Email
            current_site = get_current_site(request)
            subject = 'Activate Your CakesandMore Account'
            message = render_to_string('customer/activation/email.html', {
                'user': customer,
                'domail': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(customer.pk)),
                'token': account_activation_token.make_token(customer)
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(subject, message, to=[to_email])
            email.send()
            return redirect('customer:customer_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'customer/signup.html', {'form': form})


def customer_logout(request):
    """
    :param request:
    """
    logout(request)


def account_activation_sent(request):
    """

    :param request:
    :return:
    """
    return render(request, 'customer/activation/sent.html')


def activate(request, uidb64, token):
    """
    Activate Users
    :param request:
    :param uidb64:
    :param token:
    :return:
    """
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = get_user_model()
        customer = user.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None

    if customer is not None and account_activation_token.check_token(customer, token):
        customer.is_active = True
        customer.save()
        customer.userprofile.email_confirmed = True
        customer.userprofile.save()
        login(request, customer)
        return redirect('customer:customer-profile')
    else:
        return render(request, 'customer/activation/invalid.html')

customer/templates/customer/password/reset.html
{% extends 'customer/base.html' %}

{% block title %}Reset Password{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
          <div class="card bg-light mb-3">
            <div class="card-header">Reset your password</div>
            <div class="card-body">
              <p>Enter your email address and we will send you a link to reset your password.</p>
              <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                <div class="row">
                  <div class="col-sm-3"></div>
                  <div class="col-sm-12">
                      {% for error in field.errors %}
                      <p class="text text-danger">{{ error }}</p>
                      {% endfor %}
                  </div>
                </div>
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-12">
                        <input autofocus id="{{ field.id_for_label }}" 
                                name="{{ field.name }}" 
                                required class="form-control">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-12">
                        {% if field.help_text %}
                        <small class="text text-primary"">{{ field.help_text }}</small>
                        {% endif %}
                    </div>
                  </div>
            {% endfor %}
                <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

customer/templates/customer/password/reset_complete.html
{% extends "customer/base.html" %}

{% block title %}Password reset complete{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8 col-sm-10">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">Password changed!</h3>
              <div class="alert alert-success" role="alert">
                You have successfully changed your password! You may now proceed to log in.
              </div>
              <a href="{% url 'customer:customer-login' %}" class="btn btn-secondary btn-block">Return to log in</a>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

customer/templates/customer/password/reset_confirm.html
{% extends "customer/base.html" %}

{% block title %}
{% if validlink %}
  Change password for {{ form.user.username }}
{% else %}
  Reset your password
{% endif %}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <div class="card">
      <div class="card-header">Change password for <span><i class="ion-android-person"></i></span> {{ form.user.username }}</div>
      <div class="card-body">
        {% if validlink %}
          <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                  <div class="row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-12">
                        {% for error in field.errors %}
                        <p class="text text-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                  </div>
                  <div class="form-group row">
                      <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                      <div class="col-sm-12">
                          <input autofocus id="{{ field.id_for_label }}" 
                                  name="{{ field.name }}" 
                                  type="password"
                                  required class="form-control">
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-3"></div>
                      <div class="col-sm-12">
                          {% if field.help_text %}
                          <small class="text text-primary"">{{ field.help_text }}</small>
                          {% endif %}
                      </div>
                    </div>
              {% endfor %}
            <button type="submit" class="btn btn-success btn-block">Change password</button>
          </form>
        {% else %}
          <h3 class="card-title">Reset your password</h3>
          <div class="alert alert-danger" role="alert">
            It looks like you clicked on an invalid password reset link. Please try again.
          </div>
          <a href="{% url 'customer:customer_password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

customer/templates/customer/password/reset_done.html
{% extends 'customer/base.html' %}

{% block title %}Password reset successful{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
          <div class="card">
            <div class="card-header">Reset your password</div>
            <div class="card-body">
              <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
              <a href="{% url 'customer:customer-login' %}" class="btn btn-secondary btn-block">Return to log in</a>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

customer/templates/customer/password/reset_email.html
{% autoescape off %}

Hi there,
<p>
    Someone asked for a password reset for the email address {{ email }}.
</p>

<p>
    Follow the link below:
    {{ protocol }}://{{ domain }}{% url 'customer:customer_password_reset_confirm' uidb64=uid token=token %}
    
    In case you forgot your CakesAndMore account username: {{ user.username }}
</p>

<p>
    If clicking the link above doesn't work, please copy and paste the URL
    in a new browser window instead.
</p>

<p>
    If you've received this mail in error, it's likely that another user entered
    your email address by mistake while trying to reset a password. If you didn't
    initiate the request, you don't need to take any further action and can safely
    disregard this email.
</p>

<p>
    Thanks,
    The CakesAndMore Web Team
</p>
{% endautoescape %}